config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  resources :tweets do 
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet'
  end 

  devise_for :users
  get 'home/index'
  get 'all_tweets', to: 'home#all_tweets', as: 'all_tweets'

  #get 'users/follow'
  post 'follow/:user_id', to: 'users#follow', as: 'users_follow'

  root to: 'home#index'

  scope '/api' do 
    get '/news', to: 'api#news', as: 'api_news'
    get '/tweets_between_dates/:date1/:date2', to: 'api#tweets_between_dates', as: 'tweets_between_dates'
    post '/tweets', to: 'api#create_tweet', as: 'api_tweets'
  end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  include ActionView::Helpers::UrlHelper

  before_save :add_hashtags
  validates :content, presence: true 

  belongs_to :user
  has_many :likes
  has_many :liking_users, :through => :likes, :source => :user

  paginates_per 5

   #scope :tweets_for_me, -> (user) {where(user_id: user.friends.pluck(:friend_id))}
   scope :tweets_for_me, -> (user) { where(user_id: user.friends.pluck(:friend_id).push(user.id)) }
  
   def add_hashtags
     new_array = []
     self.content.split(" ").each do |word|
       if word.start_with?("#")
         word_parsed = word.sub '#','%23'
         word = link_to(word, Rails.application.routes.url_helpers.root_path+"?search="+word_parsed )
       end
       new_array.push(word)
     end
     self.content = new_array.join(" ")
   end

  def is_liked?(user)
    if self.liking_users.include?(user)
      true
    else
      false 
    end 
  end 

  def remove_like(user)
    Like.where(user: user, tweet: self).first.destroy
  end

  def add_like(user)
    Like.create(user: user, tweet: self)
  end 

  def like_icon(user)
    if is_liked?(user)
      'fas fa-heart'
    else
      'far fa-heart'
    end 
  end 

  def count_rt
    Tweet.where(rt_ref: self.id).count
  end

  def is_retweet?
    rt_ref ? true : false
  end

  def tweet_ref
    Tweet.find(self.rt_ref)
  end 

  def retweet_icon
    if self.count_rt > 0 
      "text-primary"
    else
      "text-muted"
    end 
  end 

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :set_current_tweet, only: [:likes, :retweet]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user 

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def likes
    #Ver si el usuario auth ya logeado le habia dado like, sino tiene que darle like, y si lo hizo quitarlo.
    if @tweet.is_liked?(current_user)
      @tweet.remove_like(current_user)
    else
      @tweet.add_like(current_user)
    end 
    redirect_to root_path
  end

  def retweet
    new_tweet = Tweet.create(content: @tweet.content, user: current_user, rt_ref: @tweet.id)
    
    redirect_to root_path 
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def set_current_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<!-- Page content holder -->

  <%= form_with(model: tweet, local: true) do |form| %>
   <% if tweet.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

       <ul>
       <% tweet.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
       </ul>
     </div>
   <% end %>

   <div class="card" >
    <div class="card-body">
        <div class="field card-title">
          <%= form.label :content, "#{current_user.username} dice: " %>
        </div>
        <div class="card-text">
          <%= form.text_area :content, id: :tweet_content, :class => "form-control" %>
        </div>

        <div class="actions text-right my-2">
          <%= form.submit "Twittear", :class => "btn btn-warning text-black" %>
        </div>
      <% end %>
    </div>
  </div> 


 
  

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<!-- Page content holder -->
<div class="page-content p-5" id="content">
  <!-- Toggle button -->
  <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Menú</small></button>
  
  <p id="notice"><%= notice %></p>

  <h1>Mis Tweets</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tweets.each do |tweet| %>
        <tr>
          <td scope="row text-black"><%= tweet.content.html_safe %></td>
          <td scope="row"><%= link_to 'Show', tweet, class: "text-white" %></td> 
          <td scope="row"><%= link_to 'Edit', edit_tweet_path(tweet), class: "text-white" %></td> 
          <td scope="row"><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-white" %></td>    
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Tweet', new_tweet_path, class: "btn btn-warning text-black" %>

</div>  

app/views/tweets/new.html.erb
<!-- Page content holder -->
<div class="page-content p-5" id="content"> 
    <h1>Nuevo Tweet</h1>

    <%= render 'form', tweet: @tweet %>

    <div class="pt-2">    
        <%= link_to 'Back', root_path, class: "btn btn-warning text-black" %>
    </div>
</div>

app/views/tweets/show.html.erb
<div class="page-content p-5" id="content">
  <!-- Toggle button -->
  <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4"><i class="fa fa-bars mr-2"></i><small class="text-uppercase font-weight-bold">Menú</small></button>

    <div class="container-fluid"> 
        <div class="row">
            <div class="col-12">
    
                <div class="card rounded mb-3">
                    <div class="card-body"> 
                        <div class="container-fluid">  
                            <div class="row">
      
                            <!-- Foto de perfil -->
                            <div class=" col-3 photo-profile p-3 d-inline">
                                <%= image_tag (@tweet.user.photo_url), :class => "photo-tweet rounded-circle img-thumbnail" %>
                                <% if user_signed_in? && current_user != @tweet.user %>
                                  <%= link_to current_user.is_following?(@tweet.user) ? 
                                  "Unfollow" : "Follow", 
                                  users_follow_path(@tweet.user.id), 
                                  class: "btn-follow",
                                  method: :post %>
                            <% end %>
                            </div>

                            <div class="col-9 d-inline content-text-card">
                                <!-- Texto RT -->
                                <div class="rt-text">
                                    <% if @tweet.is_retweet? %>
                                        <%= link_to '<i class="fas fa-retweet text-muted"></i>'.html_safe %>
                                        <%= link_to "Has retwitteado..", @tweet.tweet_ref %>   
                                    <% end %>
                                </div>

                                <!-- Nombre, fecha y contenido -->
                                <div class="index-username">
                                    <%= @tweet.user.username %>
                                </div>

                                <span class="index-calendar">
                                <%= link_to '<i class="far fa-calendar-alt fa-sm"></i> '.html_safe+distance_of_time_in_words(Time.now, @tweet.created_at), @tweet %>
                                </span>
                    
                                <!-- separador interno -->    
                                <div class="separator3"></div>

                                <div class="index-content">
                                    <%= @tweet.content.html_safe %>
                                </div>
                            </div>    

                            <!-- separador -->    
                            <div class=" col-12 separator2"></div> 
        
                            <!-- Likes y RT -->
                            <div class=" col-12">
                                <div class="float-right text-right">
                                    <span>
                                        <%= @tweet.likes.count %>       
                                            <%= link_to ('<i class="'+@tweet.like_icon(current_user) +' text-danger fa-sm"></i>').html_safe, tweet_likes_path(@tweet), method: :post %>              
                                    </span>   
                                        |         
                                    <span>
                                        <%= @tweet.count_rt %>  
                                        <%= link_to ('<i class="fas fa-retweet '+@tweet.retweet_icon+'"></i>').html_safe, tweet_retweet_path(@tweet), method: :post %>                                             
                                    </span>    
                                </div>
                            </div> 

                            </div>
                        </div> 
                    </div> 
                </div> 
            </div>                  
        </div>        
    </div>  
  

  <div>
    <% @tweet.liking_users.each do |user|%>
      <div class="">
      <%= image_tag (user.photo_url), :class => "rounded-circle photo-tweet2" %><br>
      <span class="username-text-like"><%= user.username %></span>
      </div>
    <% end %>
  </div><br>

  <%= link_to 'Back', root_path, class: "btn btn-warning text-black ml-4" %>

</div>  