config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  resources :tweets do 
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet'
  end 

  devise_for :users
  get 'home/index'
  get 'all_tweets', to: 'home#all_tweets', as: 'all_tweets'

  #get 'users/follow'
  post 'follow/:user_id', to: 'users#follow', as: 'users_follow'

  root to: 'home#index'

  scope '/api' do 
    get '/news', to: 'api#news', as: 'api_news'
    get '/tweets_between_dates/:date1/:date2', to: 'api#tweets_between_dates', as: 'tweets_between_dates'
    post '/tweets', to: 'api#create_tweet', as: 'api_tweets'
  end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<!-- Vertical navbar -->

<div class="vertical-nav color-nav" id="sidebar">
  <div class="py-4 px-3 mb-2 color-nav">
    <% if user_signed_in?%>
      <span class="media d-flex align-items-center ubicacion-foto" alt="..." width="65">
      <%=link_to image_tag(current_user.photo_url, class: 'mr-3 rounded-circle img-thumbnailshadow-sm medidas-img-profile'), tweets_path %>
      </span>  
      <div class="media-body ubicacion-name">
         <h4 class="m-0 font-name"><%= current_user.username %></h4>
         <p class="font-weight-light text-muted mb-0 font-email"><%= current_user.email %></p>
      </div>
    <%else%>
      <%= link_to '<i class="fab fa-twitter index-icon-logo"></i> '.html_safe, root_path %>    
    <%end%>
  </div>  
  
      <div class="secciones-nav">
      <% if user_signed_in?%>
        <ul class="nav flex-column color-nav mb-1">
          <li class="nav-item">
            <span class="nav-link text-black color-nav">
              <%= link_to '<i class="fas fa-home index-icon"></i> '.html_safe, root_path%>
              Home
            </span>
          </li>
    
          <li class="nav-item">
            <span class="nav-link text-black color-nav">
              <%= link_to '<i class="fas fa-globe-americas index-icon"></i> '.html_safe, all_tweets_path %>
                All Tweets
              </span>
          </li>
    
          <li class="nav-item">
            <span class="nav-link text-black color-nav">
              <%= link_to '<i class="fas fa-pen index-icon"></i> '.html_safe, new_tweet_path %>
              New Tweets
            </span>
          </li>
      <% end %>

      <!--Log out, registro y log in -->
      <% if user_signed_in? %>
          <div class="nav-item">
            <span class="nav-link text-black color-nav">
              <%= link_to '<i class="fas fa-sign-out-alt index-icon d-inline"></i>'.html_safe, destroy_user_session_path, method:  :get%> 
              Log Out
            </span>  
          </div>
      <% else %>
          <div class="nav-item pb-3">
            <span class="nav-link text-black color-nav">
              <%= link_to '<i class="fas fa-plus index-icon2 d-inline"></i>'.html_safe, new_user_registration_path %>
              Registro
            </span>  
          </div>
          <div class="nav-item">
            <span class="nav-link text-black color-nav">
              <%= link_to '<i class="fas fa-sign-in-alt index-icon2 d-inline"></i> '.html_safe, new_user_session_path%>
              Log In
            </span>  
          </div>
      <% end %>

          <div class="nav-item">
            <span class="nav-link text-black color-nav">
              <% if user_signed_in?%>
                <%= link_to '<i class="fab fa-twitter index-logo2 border-top1 text-center"></i> '.html_safe, root_path %>
              <% end %>
            </span>
          </div>

      </ul>
  </div>  

</div>

app/views/shared/_tweet.html.erb
<div class="container-fluid"> 
    <div class="row">
        <div class="col-12">
 
            <div class="card rounded mb-3">
                <div class="card-body"> 
                    <div class="container-fluid">  
                        <div class="row">
  
                        <!-- Foto de perfil -->
                        <div class=" col-3 photo-profile p-3 d-inline text-center">
                            <%= image_tag (tweet.user.photo_url), :class => "photo-tweet rounded-circle img-thumbnail" %>
                            <% if user_signed_in? && current_user != tweet.user %>
                                <%= link_to current_user.is_following?(tweet.user) ? 
                                "Unfollow" : "Follow", 
                                users_follow_path(tweet.user.id), 
                                class: "btn-follow",
                                method: :post %>
                            <% end %>
                        </div>

                        <div class="col-9 d-inline content-text-card">
                            <!-- Texto RT -->
                            <div class="rt-text">
                                <% if tweet.is_retweet? %>
                                    <%= link_to '<i class="fas fa-retweet text-muted"></i>'.html_safe %>
                                    <%= link_to "Has retwitteado..", tweet.tweet_ref %>   
                                <% end %>
                            </div>

                            <!-- Nombre, fecha y contenido -->
                            <div class="index-username">
                                <%= tweet.user.username %>
                            </div>

                            <span class="index-calendar">
                            <%= link_to '<i class="far fa-calendar-alt fa-sm"></i> '.html_safe+distance_of_time_in_words(Time.now, tweet.created_at), tweet %>
                            </span>
                
                            <!-- separador interno -->    
                             <div class="separator3"></div>

                            <div class="index-content">
                                <%= tweet.content.html_safe %>
                            </div>
                        </div>    

                        <!-- separador -->    
                        <div class=" col-12 separator2"></div> 
    
                        <!-- Likes y RT -->
                        <div class=" col-12">
                            <div class="float-right text-right">
                                <span>
                                    <%= tweet.likes.count %>       
                                        <%= link_to ('<i class="'+tweet.like_icon(current_user) +' text-danger fa-sm"></i>').html_safe, tweet_likes_path(tweet), method: :post %>              
                                </span>   
                                    |         
                                <span>
                                    <%= tweet.count_rt %>  
                                    <%= link_to ('<i class="fas fa-retweet '+tweet.retweet_icon+'"></i>').html_safe, tweet_retweet_path(tweet), method: :post %>                                             
                                </span>    
                            </div>
                        </div> 

                        </div>
                    </div> 
                 </div> 
             </div> 
        </div>                  
    </div>        
</div>             